# The product build: the page only, no Worker code and no data. Each person's
# notes are in their own Dropbox; the page talks to Dropbox (and Lemon Squeezy
# for license keys) directly. Deploy with `npm run deploy:product`.
name = "wr1t3r-user"
compatibility_date = "2026-09-01"
workers_dev = false

routes = [{ pattern = "my.wr1t3r.app", custom_domain = true }]

[assets]
directory = "./dist-product"
not_found_handling = "single-page-application"
