// Writes src/sitekeys.js: the property names the website (librarykaiju/w3bz1n3)
// reads, so Clean up properties can warn before renaming or deleting one.
// Run it again when the site's templates change:
//   node scripts/site-keys.js ../w3bz1n3
// A name counts as read when it appears as a whole word in the site's
// layouts, partials, config, data files or listing pages. That's broad on
// purpose: a false warning costs a second look, a missed one a broken page.
import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { propertyIndex } from "../src/propclean.js";

const root = process.argv[2];
if (!root) { console.error("usage: node scripts/site-keys.js <path to the w3bz1n3 checkout>"); process.exit(1); }
const walk = (dir, keep, out = []) => {
	for (const e of readdirSync(dir)) {
		if (e.startsWith(".") || e === "node_modules") continue;
		const p = join(dir, e);
		if (statSync(p).isDirectory()) walk(p, keep, out);
		else if (keep(p)) out.push(p);
	}
	return out;
};
const notes = Object.fromEntries(walk(join(root, "content"), (p) => p.endsWith(".md")).map((p) => [p, readFileSync(p, "utf8")]));
const code = [
	...walk(join(root, "_includes"), () => true),
	...walk(join(root, "_config"), () => true),
	...walk(join(root, "_data"), () => true),
	join(root, "eleventy.config.js"),
	...walk(join(root, "content"), (p) => /\.(njk|11tydata\.js)$/.test(p)),
].map((p) => readFileSync(p, "utf8")).join("\n");
const escape = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
const used = propertyIndex(notes).map((r) => r.key)
	.filter((k) => k.trim() && new RegExp(`(^|[^\\w-])${escape(k)}(?![\\w-])`, "i").test(code))
	.sort((a, b) => a.localeCompare(b));
writeFileSync(new URL("../src/sitekeys.js", import.meta.url), `// Property names the website reads (generated by scripts/site-keys.js; run
// it again when the site's templates change). Clean up properties warns
// before renaming or deleting one of these.
export const SITE_KEYS = new Set(${JSON.stringify(used, null, "\t").replace(/\n/g, "\n")});
`);
console.log(`${used.length} property names the site reads, written to src/sitekeys.js`);
