// Templates wr1t3r brings with it, for a notebook without its own
// _templates/ (a new one, say). A notebook's own template always wins; these
// only fill in when it has none, so Today and the New ... commands work from
// the first day. Same <% %> forms as a notebook's templates (src/daily.js).

const fm = (lines) => ["---", ...lines, "---", ""].join("\n");
const log = (type, extra = []) => fm([`title: "<% tp.file.title %>"`, `type: ${type}`, ...extra, "rating: []", "status:", `date: <% tp.date.now("YYYY-MM-DD") %>`, "tags: []", "publish: false"]) + "\n## Notes\n\n";

const TEMPLATES = {
	daily: fm([`date: <% tp.date.now("YYYY-MM-DD") %>`]) + "\n```wr1t3r-planner\ntasks: [crit, todo]\ntimeline: []\n```\n\n## Notes\n\n",
	journal: fm([`title: "<% tp.file.title %>"`, `date: <% tp.date.now("YYYY-MM-DD") %>`, "tags: []"]) + "\n",
	note: fm([`title: "<% tp.file.title %>"`, `date: <% tp.date.now("YYYY-MM-DD") %>`, "tags: []"]) + "\n",
	microblog: fm([`date: <% tp.date.now("YYYY-MM-DD HH:mm") %>`, "tags: []"]) + "\n",
	"catalog entry": fm([`title: "<% tp.file.title %>"`, "url:", "tags: []"]) + "\n",
	"tools entry": fm([`title: "<% tp.file.title %>"`, "url:", "tags: []"]) + "\n",
	book: log("book", ["author:", "format: []"]),
	movie: log("movie", ["director:", "year:"]),
	series: log("series", ["year:"]),
	anime: log("anime", ["studio:", "year:"]),
	music: log("music", ["artist:", "year:"]),
	game: log("game", ["platform:", "year:"]),
	podcast: log("podcast", ["host:"]),
	comic: log("comic", ["writer:", "artist:"]),
};

// Writing templates: these are listed with the notebook's own templates
// (Settings > Templates, the slash menu, Insert template) until it has one of
// the same name, and New project (src/projects.js) builds from them.
const NOW = `<% tp.date.now("YYYY-MM-DD") %>`;
const lines = (...l) => "\n" + l.join("\n") + "\n";
const piece = (extra = []) => fm(["synopsis:", "status: idea", ...extra]);
const script = (extra = []) => piece(["cssclasses:", "  - script", ...extra]);
const paper = (style, extra = []) => fm([`title: "<% tp.file.title %>"`, `style: ${style}`, "author:", ...extra, `date: ${NOW}`, "status: draft", "cssclasses:", "  - manuscript", "tags: [research]"]);

const WRITING = {
	Scene: piece(["pov:", "location:"]) + lines(
		"",
	),
	Chapter: piece(["pov:"]) + lines(
		"",
	),
	Character: fm([`title: "<% tp.file.title %>"`, "role:", "age:", "compile: false", "tags: [character]"]) + lines(
		"# <% tp.file.title %>",
		"",
		"**In one line:** ",
		"",
		"## Wants",
		"What they're after, on the surface.",
		"",
		"## Needs",
		"What they're missing and don't know it.",
		"",
		"## Flaw and wound",
		"",
		"## How they look and sound",
		"",
		"## Arc",
		"Where they start, and where the story leaves them.",
		"",
		"## Relationships",
		"",
	),
	"Style sheet": fm([`title: "<% tp.file.title %>"`, "compile: false", "tags: [style]"]) + lines(
		"# <% tp.file.title %>",
		"",
		"%% The decisions an editor would track, so the book stays consistent: one place to check how a name is spelled or whether it's \"OK\" or \"okay\". %%",
		"",
		"## Names and spellings",
		"| Word | Notes |",
		"| --- | --- |",
		"|  |  |",
		"",
		"## Style choices",
		"- Numbers: spelled out up to one hundred",
		"- Serial comma: yes",
		"- Dialogue tags: said",
		"",
		"## Timeline",
		"",
		"## Places",
		"",
	),
	Essay: fm([`title: "<% tp.file.title %>"`, `date: ${NOW}`, "status: draft", "synopsis:", "tags: [essay]"]) + lines(
		"# <% tp.file.title %>",
		"",
		"%% A shape to start from: a hook and your thesis, a paragraph for each point with its evidence, and a conclusion that answers \"so what?\". Delete these notes as you go. %%",
		"",
		"Open with a hook, then state your thesis in one sentence.",
		"",
		"First point. Give the evidence, then say what it shows and how it supports the thesis.",
		"",
		"Second point.",
		"",
		"Third point, or the strongest objection and your answer to it.",
		"",
		"Conclusion: what the reader should take away, and why it matters.",
		"",
	),
	"Research paper (MLA)": paper("MLA", ["instructor:", "course:"]) + lines(
		"%% MLA 9th edition. Page: 1-inch margins, double-spaced, 12 pt, your last name and the page number top right (Settings > Writing > Header and footer). First page, top left on separate lines: your name, instructor, course, date (7 October 2026). Then the title, centered, with no title page. Cite in the text by author and page: (Morrison 42). %%",
		"",
		"Your Name",
		"Instructor's Name",
		"Course",
		"<% tp.date.now(\"D MMMM YYYY\") %>",
		"",
		"# <% tp.file.title %>",
		"",
		"Introduce the topic and end the paragraph with your thesis (Author 12).",
		"",
		"Each body paragraph makes one claim, supports it with a quotation or paraphrase, and explains it.",
		"",
		"Conclusion.",
		"",
		"## Works Cited",
		"",
		"%% Alphabetical by author's last name, hanging indent. Book: Last, First. *Title*. Publisher, Year. Article: Last, First. \"Article Title.\" *Journal*, vol. 3, no. 2, Year, pp. 10-20. Web page: Last, First. \"Page Title.\" *Site Name*, Day Month Year, URL. %%",
		"",
		"Last, First. *Title of Book*. Publisher, Year.",
		"",
	),
	"Research paper (APA)": paper("APA", ["affiliation:", "course:", "instructor:"]) + lines(
		"%% APA 7th edition (student paper). Title page: the title in bold, centered, then your name, department and school, course, instructor and due date (Compile makes a title page from the folder's title and author). Page numbers top right. Double-spaced, 12 pt. Cite by author and year: (Nguyen, 2021) or Nguyen (2021) found... Headings: level 1 centered bold, level 2 left bold. %%",
		"",
		"# <% tp.file.title %>",
		"",
		"Introduce the problem, what's known about it (Author, 2020), and what this paper sets out to show.",
		"",
		"## Method",
		"",
		"## Results",
		"",
		"## Discussion",
		"",
		"## References",
		"",
		"%% Alphabetical by author, hanging indent. Book: Author, A. A. (Year). *Title of work: Capital letter also for subtitle*. Publisher. Article: Author, A. A., & Author, B. B. (Year). Title of article. *Journal Name, 12*(3), 45-67. https://doi.org/xx.xxx/yyyy Web page: Author, A. A. (Year, Month Day). *Title of page*. Site Name. URL %%",
		"",
		"Author, A. A. (Year). *Title of work*. Publisher.",
		"",
	),
	"Research paper (Chicago)": paper("Chicago", ["instructor:", "course:"]) + lines(
		"%% Chicago 17th edition, notes and bibliography. Title page optional (Compile makes one from the folder's title and author). Double-spaced text, 12 pt, page numbers. Cite with a footnote at the end of the sentence; the first note for a source is full, later ones short (Author, *Short Title*, page). %%",
		"",
		"# <% tp.file.title %>",
		"",
		"Introduce the question and your argument.[^1]",
		"",
		"Body paragraphs, each with its evidence and a footnote for the source.[^2]",
		"",
		"Conclusion.",
		"",
		"[^1]: First Last, *Title of Book* (City: Publisher, Year), 25.",
		"[^2]: Last, *Short Title*, 30.",
		"",
		"## Bibliography",
		"",
		"%% Alphabetical by author, hanging indent. Book: Last, First. *Title of Book*. City: Publisher, Year. Article: Last, First. \"Article Title.\" *Journal* 12, no. 3 (Year): 45-67. %%",
		"",
		"Last, First. *Title of Book*. City: Publisher, Year.",
		"",
	),
	"Script scene": script() + lines(
		"INT. LOCATION - DAY",
		"",
		"",
	),
	Screenplay: script() + lines(
		"%% Screenplay format: a scene heading (INT. or EXT., the place, DAY or NIGHT) starts each scene. A name in capitals on its own line starts dialogue; a line in (brackets) under it says how it's said. Transitions like CUT TO: sit on their own line. The editor and Compile lay it out in script format. %%",
		"",
		"FADE IN:",
		"",
		"EXT. CITY STREET - NIGHT",
		"",
		"Rain on empty pavement. A neon sign buzzes, half its letters dark.",
		"",
		"MAYA (30s, soaked, out of time) hurries past with a phone to her ear.",
		"",
		"MAYA",
		"(into the phone)",
		"I'm two minutes away. Don't let them start without me.",
		"",
		"She stops under the sign and looks up.",
		"",
		"CUT TO:",
		"",
		"INT. DINER - CONTINUOUS",
		"",
		"",
	),
	"TV script": script(["episode:", "season:"]) + lines(
		"%% A TV episode: a cold open, then acts, each ending with END OF ACT. Each act starts on a new page when compiled with New page between notes. Scene headings, dialogue and transitions work as in a screenplay. %%",
		"",
		"## COLD OPEN",
		"",
		"FADE IN:",
		"",
		"INT. LOCATION - DAY",
		"",
		"What we see.",
		"",
		"CHARACTER",
		"What they say.",
		"",
		"END OF COLD OPEN",
		"",
		"## ACT ONE",
		"",
		"INT. LOCATION - NIGHT",
		"",
		"",
		"END OF ACT ONE",
		"",
		"## ACT TWO",
		"",
		"",
		"END OF ACT TWO",
		"",
	),
	"Comic script": piece(["issue:", "pages:"]) + lines(
		"%% A comic script: a heading for each page, then each panel. Describe what the artist should draw, then the lettering: CAPTION for narration, a name for a balloon, SFX for sound effects. Say whether the page turns (odd pages are on the right). %%",
		"",
		"## Page 1",
		"",
		"### Panel 1",
		"",
		"Wide shot. Where we are, who's there, what they're doing.",
		"",
		"**CAPTION:** Narration.",
		"",
		"**MAYA:** Dialogue.",
		"",
		"### Panel 2",
		"",
		"Close on Maya.",
		"",
		"**MAYA (small):** A quieter line.",
		"",
		"**SFX:** KRAK",
		"",
		"## Page 2",
		"",
		"### Panel 1",
		"",
		"",
	),
};

const KEYS = new Map(Object.keys(WRITING).map((k) => [k.toLowerCase(), k]));

// The built-in text for a template path ("_templates/Daily.md"), or null.
export function builtinTemplate(name) {
	const key = String(name || "").toLowerCase().replace(/^.*_templates\//, "").replace(/\.md$/, "");
	return TEMPLATES[key] ?? (KEYS.has(key) ? WRITING[KEYS.get(key)] : null);
}

// The writing templates: [{ name, text }], in a sensible order.
export const writingTemplates = () => Object.entries(WRITING).map(([name, text]) => ({ name, text }));
