// Writing prompts for the empty screen: one a day (the same on every device,
// like the quote); a tap starts a note with it and ↻ shows another. Questions, not assignments, so
// they work for a journal entry, an essay or a scene.

import { dayNumber } from "./quotes.js";

export const PROMPTS = [
	"What's a smell that takes you straight back to childhood, and where does it take you?",
	"What did you believe at twelve that you'd give anything to believe again?",
	"Who taught you something without meaning to?",
	"What room do you know best in the world? Walk through it.",
	"What's the kindest thing a stranger has done for you?",
	"What are you avoiding writing about, and why?",
	"What would you say to the person you were five years ago?",
	"What does your hometown get wrong about itself?",
	"What's a rule you follow that nobody taught you?",
	"When did you last change your mind about something that mattered?",
	"What object in your home has the best story?",
	"What does your ordinary Tuesday look like, hour by hour?",
	"What's a place you can never go back to?",
	"Who do you miss that you never got to say goodbye to?",
	"What would a character who wants the opposite of you want?",
	"What's the first thing you remember making with your hands?",
	"What song do you know every word to, and why that one?",
	"What secret would a stranger guess about you from your kitchen?",
	"What's a meal you'd cook for someone you're trying to impress?",
	"What does courage look like in a small moment?",
	"Write the argument you wish you'd won. What did the other side get right?",
	"What sound do you hear right now that you'd usually ignore?",
	"Which book changed how you see something, and what did it change?",
	"What's a job you had that taught you about people?",
	"What would you do with a free, empty year?",
	"What's the best advice you ignored?",
	"Describe someone you love by their hands.",
	"What's a tradition you kept, and one you let go?",
	"When were you most lost, literally or otherwise?",
	"What would your ideal day of work look like, start to finish?",
	"What story does your family tell about you that isn't quite true?",
	"What are you proud of that nobody else knows about?",
	"What's the view from the window you look out of most?",
	"If a letter arrived from your future self, what would the first line say?",
	"What's something small that made today better than yesterday?",
	"What do you collect, even by accident?",
	"Who is the most interesting person you've met only once?",
	"What's a word you love the sound of, and what does it make you think of?",
	"What would you write if nobody would ever read it?",
	"What scares you about the thing you want most?",
	"Describe a storm you remember.",
	"What does home feel like when you walk back in after a long trip?",
	"What's an unpopular opinion you'd defend all day?",
	"What's something you've made that failed, and what did it teach you?",
	"Who would you want to have dinner with, and what would you order?",
	"What does your work look like to someone who has never seen it?",
	"Where do you go when you need to think?",
	"What would a stranger overhear at your favorite café?",
	"What's a promise you kept that was hard to keep?",
	"What do you want to be remembered for?",
	"What's the oldest thing you own, and how did you get it?",
	"What changed the year everything changed?",
	"Write about a door. Who's behind it?",
	"What's something you're still learning to do well?",
	"What question do you wish someone would ask you?",
	"What did the last walk you took notice for you?",
	"What makes a place feel like it's yours?",
	"What would you tell a new writer who's afraid to start?",
	"What happened next, after the ending of your favorite story?",
	"What's the truest sentence you can write about today?",
];

export function promptFor(date = new Date(), step = 0) {
	const n = PROMPTS.length;
	return PROMPTS[(((dayNumber(date) + step) % n) + n) % n];
}
